import { execFile as execFileCallback } from 'node:child_process'
import path from 'node:path'
import { promisify } from 'node:util'
import type { PackageDefinition } from './types.js'

const execFile = promisify(execFileCallback)

export interface GitRunner {
  run(command: string, args: string[], cwd?: string): Promise<string>
}

const hostGitRunner: GitRunner = {
  async run(command, args, cwd) {
    const result = await execFile(command, args, { cwd })
    return result.stdout
  }
}

export interface PullRequestOptions {
  token: string
  repository: string
  baseBranch: string
  updateBranch: string
  packages: PackageDefinition[]
  autoMerge: boolean
}

export async function createUpdatePullRequest(
  workspace: string,
  options: PullRequestOptions,
  git: GitRunner = hostGitRunner
): Promise<string | null> {
  validateBranchName(options.updateBranch)
  const packagePaths = options.packages.map((pkg) =>
    getRelativePackagePath(workspace, pkg.path)
  )

  await git.run('git', ['add', '--', ...packagePaths], workspace)

  const changed = await git.run(
    'git',
    ['diff', '--cached', '--name-only'],
    workspace
  )
  if (!changed.trim()) return null

  await git.run(
    'git',
    ['config', 'user.name', 'github-actions[bot]'],
    workspace
  )
  await git.run(
    'git',
    [
      'config',
      'user.email',
      '41898282+github-actions[bot]@users.noreply.github.com'
    ],
    workspace
  )
  await git.run(
    'git',
    ['commit', '-m', 'chore: update AUR packages'],
    workspace
  )

  const commit = (await git.run('git', ['rev-parse', 'HEAD'], workspace)).trim()
  const remoteBranch = options.updateBranch

  if (await remoteBranchExists(git, workspace, remoteBranch)) {
    await git.run('git', ['fetch', 'origin', options.updateBranch], workspace)
    await git.run(
      'git',
      [
        'switch',
        '-c',
        options.updateBranch,
        '--track',
        'origin/' + options.updateBranch
      ],
      workspace
    )
    await git.run('git', ['cherry-pick', commit], workspace)
  } else {
    await git.run('git', ['switch', '-c', options.updateBranch], workspace)
  }

  await git.run(
    'git',
    ['push', '--set-upstream', 'origin', options.updateBranch],
    workspace
  )

  const [owner, repo] = options.repository.split('/')
  if (!owner || !repo) {
    throw new Error('GITHUB_REPOSITORY must use owner/name form')
  }

  const existing = await requestGitHub(
    options.token,
    `/repos/${owner}/${repo}/pulls?state=open&head=${encodeURIComponent(
      owner + ':' + options.updateBranch
    )}&base=${encodeURIComponent(options.baseBranch)}`
  )

  const pullRequests = Array.isArray(existing) ? existing : []
  const current = pullRequests[0]
  if (isPullRequest(current)) {
    if (options.autoMerge) await enableAutoMerge(options.token, current)
    return current.html_url
  }

  const created = await requestGitHub(
    options.token,
    `/repos/${owner}/${repo}/pulls`,
    'POST',
    {
      title: 'chore: update AUR packages',
      body: 'Automated package updates generated by aur-maintainer.',
      head: options.updateBranch,
      base: options.baseBranch
    }
  )

  if (!isPullRequest(created)) {
    throw new Error('GitHub did not return the created pull request URL')
  }

  if (options.autoMerge) await enableAutoMerge(options.token, created)
  return created.html_url
}

async function enableAutoMerge(
  token: string,
  pullRequest: PullRequest
): Promise<void> {
  if (!pullRequest.node_id || !pullRequest.head?.sha) {
    throw new Error(
      'GitHub did not return the pull request node ID or head SHA'
    )
  }

  const response = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      accept: 'application/vnd.github+json',
      authorization: 'Bearer ' + token,
      'content-type': 'application/json',
      'x-github-api-version': '2026-03-10',
      'user-agent': 'aur-maintainer'
    },
    body: JSON.stringify({
      query:
        'mutation($input: EnablePullRequestAutoMergeInput!) { enablePullRequestAutoMerge(input: $input) { pullRequest { id } } }',
      variables: {
        input: {
          pullRequestId: pullRequest.node_id,
          expectedHeadOid: pullRequest.head.sha,
          mergeMethod: 'SQUASH'
        }
      }
    })
  })

  const payload = (await response.json()) as {
    errors?: Array<{ message?: string }>
  }
  if (!response.ok || payload.errors?.length) {
    const message = payload.errors?.[0]?.message
    throw new Error(
      `GitHub auto-merge request failed: ${message ?? response.statusText}`
    )
  }
}

async function remoteBranchExists(
  git: GitRunner,
  workspace: string,
  branch: string
): Promise<boolean> {
  try {
    await git.run(
      'git',
      ['ls-remote', '--exit-code', '--heads', 'origin', branch],
      workspace
    )
    return true
  } catch (error) {
    if (isGitExitCode(error, 2)) return false
    throw error
  }
}

async function requestGitHub(
  token: string,
  path: string,
  method = 'GET',
  body?: Record<string, string>
): Promise<unknown> {
  const response = await fetch('https://api.github.com' + path, {
    method,
    headers: {
      accept: 'application/vnd.github+json',
      authorization: 'Bearer ' + token,
      'x-github-api-version': '2026-03-10',
      'user-agent': 'aur-maintainer'
    },
    body: body ? JSON.stringify(body) : undefined
  })

  if (!response.ok) {
    throw new Error(
      `GitHub API request failed: ${response.status} ${response.statusText}`
    )
  }

  return response.json()
}

function getRelativePackagePath(
  workspace: string,
  packagePath: string
): string {
  const relative = path.relative(workspace, packagePath)
  if (
    relative === '' ||
    relative.startsWith('..') ||
    path.isAbsolute(relative)
  ) {
    throw new Error('Package path must be inside the workspace')
  }
  return relative
}

function validateBranchName(branch: string): void {
  if (
    branch.length === 0 ||
    branch.startsWith('-') ||
    branch.includes('..') ||
    branch.includes(' ')
  ) {
    throw new Error('Invalid update branch name')
  }
}

function isGitExitCode(error: unknown, code: number): boolean {
  return (
    typeof error === 'object' &&
    error !== null &&
    'status' in error &&
    error.status === code
  )
}

interface PullRequest {
  html_url: string
  node_id?: string
  head?: { sha: string }
}

function isPullRequest(value: unknown): value is PullRequest {
  if (
    typeof value !== 'object' ||
    value === null ||
    !('html_url' in value) ||
    typeof value.html_url !== 'string'
  ) {
    return false
  }

  if (
    'node_id' in value &&
    value.node_id !== undefined &&
    typeof value.node_id !== 'string'
  ) {
    return false
  }

  if ('head' in value && value.head !== undefined) {
    const head = value.head
    if (
      typeof head !== 'object' ||
      head === null ||
      !('sha' in head) ||
      typeof head.sha !== 'string'
    ) {
      return false
    }
  }

  return true
}
