import { execFile as execFileCallback } from 'node:child_process'
import path from 'node:path'
import { promisify } from 'node:util'
import type { PackageDefinition } from './types.js'

const execFile = promisify(execFileCallback)

export interface GitRunner {
  run(command: string, args: string[], cwd?: string): Promise<string>
}

const hostGitRunner: GitRunner = {
  async run(command, args, cwd) {
    const result = await execFile(command, args, {
      cwd,
      env: { ...process.env, LC_ALL: 'C' }
    })
    return result.stdout
  }
}

export interface PullRequestOptions {
  token: string
  repository: string
  baseBranch: string
  updateBranch: string
  packages: PackageDefinition[]
  autoMerge: boolean
}

export async function createUpdatePullRequest(
  workspace: string,
  options: PullRequestOptions,
  git: GitRunner = hostGitRunner
): Promise<string | null> {
  if (options.packages.length !== 1) {
    throw new Error('Exactly one package is required per update pull request')
  }

  const pkg = options.packages[0]
  const relative = getRelativePackagePath(workspace, pkg.path)
  const packagePaths = [
    path.join(relative, 'PKGBUILD'),
    path.join(relative, '.SRCINFO')
  ]
  const branch = getPackageUpdateBranch(options.updateBranch, pkg.name)
  validateBranchName(branch)

  await git.run('git', ['add', '--', ...packagePaths], workspace)
  const changed = await git.run(
    'git',
    ['diff', '--cached', '--name-only'],
    workspace
  )
  if (!changed.trim()) return null

  await git.run('git', ['switch', options.baseBranch], workspace)
  await git.run('git', ['switch', '-C', branch], workspace)
  await git.run('git', ['config', 'user.name', 'github-actions[bot]'], workspace)
  await git.run(
    'git',
    [
      'config',
      'user.email',
      '41898282+github-actions[bot]@users.noreply.github.com'
    ],
    workspace
  )
  await git.run('git', ['commit', '-m', `chore: update ${pkg.name}`], workspace)
  await git.run(
    'git',
    ['push', '--force', '--set-upstream', 'origin', branch],
    workspace
  )

  const [owner, repo] = options.repository.split('/')
  if (!owner || !repo) {
    throw new Error('GITHUB_REPOSITORY must use owner/name form')
  }

  const existing = await requestGitHub(
    options.token,
    `/repos/${owner}/${repo}/pulls?state=open&head=${encodeURIComponent(
      owner + ':' + branch
    )}&base=${encodeURIComponent(options.baseBranch)}`
  )
  const pullRequests = Array.isArray(existing) ? existing : []
  const current = pullRequests[0]
  if (isPullRequest(current)) {
    if (options.autoMerge) await enableAutoMerge(options.token, current)
    await git.run('git', ['switch', options.baseBranch], workspace)
    return current.html_url
  }

  const created = await requestGitHub(
    options.token,
    `/repos/${owner}/${repo}/pulls`,
    'POST',
    {
      title: `chore: update ${pkg.name}`,
      body: `Automated update for ${pkg.name} generated by aur-maintainer.`,
      head: branch,
      base: options.baseBranch
    }
  )
  if (!isPullRequest(created)) {
    throw new Error('GitHub did not return the created pull request URL')
  }
  if (options.autoMerge) await enableAutoMerge(options.token, created)
  await git.run('git', ['switch', options.baseBranch], workspace)
  return created.html_url
}

function getPackageUpdateBranch(prefix: string, packageName: string): string {
  return prefix.replace(/\/$/, '') + '/' + packageName
}

async function enableAutoMerge(
  token: string,
  pullRequest: PullRequest
): Promise<void> {
  if (!pullRequest.node_id || !pullRequest.head?.sha) {
    throw new Error(
      'GitHub did not return the pull request node ID or head SHA'
    )
  }

  const response = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      accept: 'application/vnd.github+json',
      authorization: 'Bearer ' + token,
      'content-type': 'application/json',
      'x-github-api-version': '2026-03-10',
      'user-agent': 'aur-maintainer'
    },
    body: JSON.stringify({
      query:
        'mutation($input: EnablePullRequestAutoMergeInput!) { enablePullRequestAutoMerge(input: $input) { pullRequest { id } } }',
      variables: {
        input: {
          pullRequestId: pullRequest.node_id,
          expectedHeadOid: pullRequest.head.sha,
          mergeMethod: 'SQUASH'
        }
      }
    })
  })

  const payload = (await response.json()) as {
    errors?: Array<{ message?: string }>
  }
  if (!response.ok || payload.errors?.length) {
    const message = payload.errors?.[0]?.message
    throw new Error(
      `GitHub auto-merge request failed: ${message ?? response.statusText}`
    )
  }
}

interface PullRequest {
  html_url: string
  node_id?: string
  head?: { sha: string }
}

function isPullRequest(value: unknown): value is PullRequest {
  if (
    typeof value !== 'object' ||
    value === null ||
    !('html_url' in value) ||
    typeof value.html_url !== 'string'
  ) {
    return false
  }

  if (
    'node_id' in value &&
    value.node_id !== undefined &&
    typeof value.node_id !== 'string'
  ) {
    return false
  }

  if ('head' in value && value.head !== undefined) {
    const head = value.head
    if (
      typeof head !== 'object' ||
      head === null ||
      !('sha' in head) ||
      typeof head.sha !== 'string'
    ) {
      return false
    }
  }

  return true
}
