import { execFile as execFileCallback } from 'node:child_process'
import path from 'node:path'
import { promisify } from 'node:util'
import type { PackageDefinition } from './types.js'

const execFile = promisify(execFileCallback)
const AUTO_MERGE_POLL_INTERVAL_MS = 10_000

export interface GitRunner {
  run(command: string, args: string[], cwd?: string): Promise<string>
}

const hostGitRunner: GitRunner = {
  async run(command, args, cwd) {
    const result = await execFile(command, args, {
      cwd,
      env: { ...process.env, LC_ALL: 'C' }
    })
    return result.stdout
  }
}

export async function requestGitHub(
  token: string,
  path: string,
  method = 'GET',
  body?: Record<string, string>
): Promise<unknown> {
  const response = await fetch('https://api.github.com' + path, {
    method,
    headers: {
      accept: 'application/vnd.github+json',
      authorization: 'Bearer ' + token,
      'x-github-api-version': '2026-03-10',
      'user-agent': 'aur-maintainer'
    },
    body: body ? JSON.stringify(body) : undefined
  })

  if (!response.ok) {
    throw new Error(
      `GitHub API request failed: ${response.status} ${response.statusText}`
    )
  }

  if (response.status === 204) return undefined
  return response.json()
}

function getRelativePackagePath(
  workspace: string,
  packagePath: string
): string {
  const relative = path.relative(workspace, packagePath)
  if (
    relative === '' ||
    relative.startsWith('..') ||
    path.isAbsolute(relative)
  ) {
    throw new Error('Package path must be inside the workspace')
  }
  return relative
}

function validateBranchName(branch: string): void {
  if (
    branch.length === 0 ||
    branch.startsWith('-') ||
    branch.includes('..') ||
    branch.includes(' ')
  ) {
    throw new Error('Invalid update branch name')
  }
}

interface PullRequestOptions {
  token: string
  repository: string
  baseBranch: string
  updateBranch: string
  packages: PackageDefinition[]
  autoMerge: boolean
  autoMergeTimeoutSeconds: number
  validationWorkflow?: string
}

export async function createUpdatePullRequest(
  workspace: string,
  options: PullRequestOptions,
  git: GitRunner = hostGitRunner
): Promise<string | null> {
  if (options.packages.length !== 1) {
    throw new Error('Exactly one package is required per update pull request')
  }

  const pkg = options.packages[0]
  const relative = getRelativePackagePath(workspace, pkg.path)
  const packagePaths = [
    path.join(relative, 'PKGBUILD'),
    path.join(relative, '.SRCINFO')
  ]
  const branch = getPackageUpdateBranch(options.updateBranch, pkg.name)
  validateBranchName(branch)

  await git.run('git', ['add', '--', ...packagePaths], workspace)
  const changed = await git.run(
    'git',
    ['diff', '--cached', '--name-only'],
    workspace
  )
  if (!changed.trim()) return null

  await git.run('git', ['switch', options.baseBranch], workspace)
  await git.run('git', ['switch', '-C', branch], workspace)
  await git.run(
    'git',
    ['config', 'user.name', 'github-actions[bot]'],
    workspace
  )
  await git.run(
    'git',
    [
      'config',
      'user.email',
      '41898282+github-actions[bot]@users.noreply.github.com'
    ],
    workspace
  )
  await git.run('git', ['commit', '-m', `update: ${pkg.name}`], workspace)
  await git.run(
    'git',
    ['push', '--force', '--set-upstream', 'origin', branch],
    workspace
  )

  const [owner, repo] = options.repository.split('/')
  if (!owner || !repo)
    throw new Error('GITHUB_REPOSITORY must use owner/name form')

  const existing = await requestGitHub(
    options.token,
    `/repos/${owner}/${repo}/pulls?state=open&head=${encodeURIComponent(
      owner + ':' + branch
    )}&base=${encodeURIComponent(options.baseBranch)}`
  )
  const pullRequests = Array.isArray(existing) ? existing : []
  const current = pullRequests[0]
  if (isPullRequest(current)) {
    if (options.autoMerge) {
      if (options.validationWorkflow) {
        const validationRunId = await dispatchValidationWorkflow(
          options.token,
          owner,
          repo,
          options.validationWorkflow,
          branch,
          new Date().toISOString()
        )
      }
      await waitForWorkflowRunAndMerge(
        options.token,
        options.repository,
        current,
        validationRunId,
        options.autoMergeTimeoutSeconds
      )
    }
    await git.run('git', ['switch', options.baseBranch], workspace)
    return current.html_url
  }

  const created = await requestGitHub(
    options.token,
    `/repos/${owner}/${repo}/pulls`,
    'POST',
    {
      title: `update: ${pkg.name}`,
      body: `Automated update for ${pkg.name} generated by aur-maintainer.`,
      head: branch,
      base: options.baseBranch
    }
  )
  if (!isPullRequest(created))
    throw new Error('GitHub did not return the created pull request URL')
  if (options.autoMerge) {
    await waitForChecksAndMerge(
      options.token,
      options.repository,
      created,
      options.autoMergeTimeoutSeconds
    )
  }
  await git.run('git', ['switch', options.baseBranch], workspace)
  return created.html_url
}

function getPackageUpdateBranch(prefix: string, packageName: string): string {
  return prefix.replace(/\/$/, '') + '/' + packageName
}

async function dispatchValidationWorkflow(
  token: string,
  owner: string,
  repo: string,
  workflow: string,
  ref: string,
  minimumCreatedAt: string
): Promise<number> {
  await requestGitHub(
    token,
    `/repos/${owner}/${repo}/actions/workflows/${encodeURIComponent(
      workflow
    )}/dispatches`,
    'POST',
    { ref }
  )

  const deadline = Date.now() + 30_000
  while (Date.now() < deadline) {
    const response = await requestGitHub(
      token,
      `/repos/${owner}/${repo}/actions/workflows/${encodeURIComponent(
        workflow
      )}/runs?branch=${encodeURIComponent(ref)}&event=workflow_dispatch&per_page=10`
    )
    if (isWorkflowRunsResponse(response)) {
      const run = response.workflow_runs.find(
        (candidate) =>
          candidate.created_at >= minimumCreatedAt && candidate.head_sha
      )
      if (run) return run.id
    }

    await new Promise((resolve) =>
      setTimeout(
        resolve,
        Math.min(
          AUTO_MERGE_POLL_INTERVAL_MS,
          Math.max(0, deadline - Date.now())
        )
      )
    )
  }

  throw new Error(
    'Timed out waiting for dispatched validation workflow after 30 seconds'
  )
}

async function waitForWorkflowRunAndMerge(
  token: string,
  repository: string,
  pullRequest: PullRequest,
  workflowRunId: number,
  timeoutSeconds: number
): Promise<void> {
  if (!Number.isInteger(timeoutSeconds) || timeoutSeconds < 1) {
    throw new Error('auto-merge-timeout must be a positive integer')
  }

  const deadline = Date.now() + timeoutSeconds * 1000
  const [owner, repo] = repository.split('/')
  if (!owner || !repo) {
    throw new Error('GITHUB_REPOSITORY must use owner/name form')
  }

  while (Date.now() < deadline) {
    const response = await requestGitHub(
      token,
      `/repos/${owner}/${repo}/actions/runs/${workflowRunId}`
    )
    if (isWorkflowRunResponse(response) && response.status === 'completed') {
      if (
        response.conclusion !== 'success' &&
        response.conclusion !== 'neutral' &&
        response.conclusion !== 'skipped'
      ) {
        throw new Error(
          `Pull request validation workflow failed: ${response.conclusion ?? 'unknown'}`
        )
      }

      await squashMergePullRequest(token, pullRequest)
      return
    }

    await new Promise((resolve) =>
      setTimeout(
        resolve,
        Math.min(
          AUTO_MERGE_POLL_INTERVAL_MS,
          Math.max(0, deadline - Date.now())
        )
      )
    )
  }

  throw new Error(
    `Timed out waiting for pull request checks after ${timeoutSeconds} seconds`
  )
}

async function waitForChecksAndMerge(
  token: string,
  repository: string,
  pullRequest: PullRequest,
  timeoutSeconds: number
): Promise<void> {
  if (!Number.isInteger(timeoutSeconds) || timeoutSeconds < 1) {
    throw new Error('auto-merge-timeout must be a positive integer')
  }

  const deadline = Date.now() + timeoutSeconds * 1000
  const [owner, repo] = repository.split('/')
  if (!owner || !repo)
    throw new Error('GITHUB_REPOSITORY must use owner/name form')
  if (!pullRequest.head?.sha) {
    throw new Error('GitHub did not return the pull request head SHA')
  }

  while (Date.now() < deadline) {
    const checks = await requestGitHub(
      token,
      `/repos/${owner}/${repo}/commits/${pullRequest.head.sha}/check-runs?per_page=100`
    )
    const checkRuns = isCheckRunsResponse(checks) ? checks.check_runs : []

    if (
      checkRuns.length > 0 &&
      checkRuns.every((check) => check.status === 'completed')
    ) {
      const failed = checkRuns.find(
        (check) =>
          check.conclusion !== 'success' &&
          check.conclusion !== 'neutral' &&
          check.conclusion !== 'skipped'
      )
      if (failed) {
        throw new Error(
          `Pull request checks failed: ${failed.name} (${failed.conclusion ?? 'unknown'})`
        )
      }
      await squashMergePullRequest(token, pullRequest)
      return
    }

    await new Promise((resolve) =>
      setTimeout(
        resolve,
        Math.min(
          AUTO_MERGE_POLL_INTERVAL_MS,
          Math.max(0, deadline - Date.now())
        )
      )
    )
  }

  throw new Error(
    `Timed out waiting for pull request checks after ${timeoutSeconds} seconds`
  )
}

async function squashMergePullRequest(
  token: string,
  pullRequest: PullRequest
): Promise<void> {
  if (!pullRequest.node_id || !pullRequest.head?.sha) {
    throw new Error(
      'GitHub did not return the pull request node ID or head SHA'
    )
  }

  const response = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      accept: 'application/vnd.github+json',
      authorization: 'Bearer ' + token,
      'content-type': 'application/json',
      'x-github-api-version': '2026-03-10',
      'user-agent': 'aur-maintainer'
    },
    body: JSON.stringify({
      query:
        'mutation($input: MergePullRequestInput!) { mergePullRequest(input: $input) { pullRequest { id } } }',
      variables: {
        input: {
          pullRequestId: pullRequest.node_id,
          expectedHeadOid: pullRequest.head.sha,
          mergeMethod: 'SQUASH'
        }
      }
    })
  })

  const payload = (await response.json()) as {
    errors?: Array<{ message?: string }>
  }
  if (!response.ok || payload.errors?.length) {
    const message = payload.errors?.[0]?.message
    throw new Error(
      `GitHub squash merge failed: ${message ?? response.statusText}`
    )
  }
}

interface PullRequest {
  html_url: string
  number?: number
  node_id?: string
  head?: { sha: string }
}

interface WorkflowRun {
  id: number
  status: string
  conclusion: string | null
  created_at: string
  head_sha?: string
}

interface WorkflowRunsResponse {
  workflow_runs: WorkflowRun[]
}

function isWorkflowRunsResponse(value: unknown): value is WorkflowRunsResponse {
  if (
    typeof value !== 'object' ||
    value === null ||
    !('workflow_runs' in value) ||
    !Array.isArray(value.workflow_runs)
  ) {
    return false
  }

  return value.workflow_runs.every(
    (run): run is WorkflowRun =>
      typeof run === 'object' &&
      run !== null &&
      'id' in run &&
      typeof run.id === 'number' &&
      'status' in run &&
      typeof run.status === 'string' &&
      'conclusion' in run &&
      (typeof run.conclusion === 'string' || run.conclusion === null) &&
      'created_at' in run &&
      typeof run.created_at === 'string'
  )
}

function isWorkflowRunResponse(value: unknown): value is WorkflowRun {
  return (
    typeof value === 'object' &&
    value !== null &&
    'id' in value &&
    typeof value.id === 'number' &&
    'status' in value &&
    typeof value.status === 'string' &&
    'conclusion' in value &&
    (typeof value.conclusion === 'string' || value.conclusion === null)
  )
}

interface CheckRun {
  name: string
  status: string
  conclusion: string | null
}

interface CheckRunsResponse {
  check_runs: CheckRun[]
}

function isCheckRunsResponse(value: unknown): value is CheckRunsResponse {
  if (
    typeof value !== 'object' ||
    value === null ||
    !('check_runs' in value) ||
    !Array.isArray(value.check_runs)
  ) {
    return false
  }

  return value.check_runs.every(
    (check): check is CheckRun =>
      typeof check === 'object' &&
      check !== null &&
      'name' in check &&
      typeof check.name === 'string' &&
      'status' in check &&
      typeof check.status === 'string' &&
      'conclusion' in check &&
      (typeof check.conclusion === 'string' || check.conclusion === null)
  )
}

function isPullRequest(value: unknown): value is PullRequest {
  if (
    typeof value !== 'object' ||
    value === null ||
    !('html_url' in value) ||
    typeof value.html_url !== 'string'
  ) {
    return false
  }

  if (
    'number' in value &&
    value.number !== undefined &&
    typeof value.number !== 'number'
  ) {
    return false
  }

  if (
    'node_id' in value &&
    value.node_id !== undefined &&
    typeof value.node_id !== 'string'
  ) {
    return false
  }

  if ('head' in value && value.head !== undefined) {
    const head = value.head
    if (
      typeof head !== 'object' ||
      head === null ||
      !('sha' in head) ||
      typeof head.sha !== 'string'
    ) {
      return false
    }
  }

  return true
}
