name: Generate Dist Debug

on:
  push:
    branches:
      - feat/create-update-pull-request

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: feat/create-update-pull-request
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run bundle
      - name: Commit Dist
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          if git diff --quiet -- dist; then
            exit 0
          fi
          git add dist
          git commit -m "chore: update bundled action"
          git push origin HEAD:feat/create-update-pull-request
